---

- name: Install NeoFS IR binary
  ansible.builtin.get_url:
    url: '{{ neofs_ir__bin_url }}'
    dest: '{{ neofs_ir__bin_path }}'
    force: yes
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: [ 'Restart NeoFS IR' ]
  when: not (neofs_ir__use_compose | bool)
