---

- name: Download NeoFS IR binary
  ansible.builtin.get_url:
    url: '{{ neofs_ir__bin_url }}'
    dest: '{{ neofs_ir__bin_path }}'
    force: yes
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: [ 'Restart NeoFS IR' ]
  register: download_result
  retries: 5
  delay: 5
  until: not download_result.failed
  ignore_errors: '{{ ansible_check_mode }}'
