---

- name: Download neofs-cli binary
  ansible.builtin.get_url:
    url: '{{ neofs_ir__cli_bin_url }}'
    dest: '{{ neofs_ir__cli_bin_path }}'
    force: yes
    owner: 'root'
    group: 'root'
    mode: '0755'
