---

- name: Download neofs-cli binary
  ansible.builtin.get_url:
    url: '{{ neofs_ir__cli_bin_url }}'
    dest: '{{ neofs_ir__cli_bin_path }}'
    force: yes
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: neofs_ir__binaries_download | bool
  register: download_result
  retries: 5
  delay: 5
  until: download_result.status_code != '200'
