---

- name: Getting entries from NSS
  ansible.builtin.getent:
    database: passwd
    key: '{{ neofs_ir__user }}'

- name: Copy docker-compose file
  ansible.builtin.template:
    src: 'docker-compose.yml.j2'
    dest: '{{ neofs_ir__conf_dir }}/docker-compose.yml'
    owner: 'root'
    group: '{{ neofs_ir__group }}'
    mode: '0640'
  notify: [ 'Restart NeoFS IR' ]

- name: Copy dockerized systemd unit
  ansible.builtin.template:
    src: 'neofs-ir_compose.service.j2'
    dest: '/etc/systemd/system/neofs-ir{{ neofs_ir__instance }}.service'
  notify: [ 'Restart NeoFS IR' ]
