---

- ansible.builtin.include_tasks: user.yml

- name: Create configuration directory parent
  ansible.builtin.file:
    state: directory
    path: '{{ neofs_ir__conf_dir | realpath | dirname }}'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Create configuration directory
  ansible.builtin.file:
    state: directory
    path: '{{ neofs_ir__conf_dir }}'
    owner: 'root'
    group: '{{ neofs_ir__group }}'
    mode: '0750'

- name: Create data directory
  ansible.builtin.file:
    state: directory
    path: '{{ neofs_ir__data_dir }}'
    owner: '{{ neofs_ir__user }}'
    group: '{{ neofs_ir__group }}'
    mode: '0750'

- ansible.builtin.include_tasks: wallet.yml

- ansible.builtin.include_tasks: tls.yml

- name: Copy NeoFS IR config
  ansible.builtin.template:
    src: 'config.yml.j2'
    dest: '{{ neofs_ir__config_path }}'
    owner: 'root'
    group: '{{ neofs_ir__group }}'
    mode: '0640'
  notify: [ 'Restart NeoFS IR' ]

- name: Download locode database
  ansible.builtin.get_url:
    url: '{{ neofs_ir__locodedb_url }}'
    dest: '{{ neofs_ir__locodedb_path }}'
    force: yes
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart NeoFS IR' ]
  register: locode_download_result
  retries: 5
  delay: 5
  until: locode_download_result.status_code != '200'
  ignore_errors: '{{ ansible_check_mode }}'

- ansible.builtin.include_tasks: binary.yml
  when: not neofs_ir__use_docker|bool and neofs_ir__binaries_download|bool

- ansible.builtin.include_tasks: cli.yml
  when: neofs_ir__binaries_download|bool

- name: Copy systemd unit
  ansible.builtin.template:
    src: 'neofs-ir.service.j2'
    dest: '/etc/systemd/system/neofs-ir{{ neofs_ir__instance }}.service'
  notify: [ 'Restart NeoFS IR' ]
  when: not neofs_ir__use_docker|bool

- ansible.builtin.include_tasks: docker.yml
  when: neofs_ir__use_docker|bool

- ansible.builtin.include_tasks: healthcheck.yml

- name: Force debops.ferm run
  ansible.builtin.include_role:
    name: debops.debops.ferm
  vars:
    ferm__dependent_rules:
      - '{{ neofs_ir__ferm__dependent_rules }}'
  when: neofs_ir__debops_ferm_import|bool
