---

- name: Create NeoFS IR group
  ansible.builtin.group:
    name: '{{ neofs_ir__group }}'
    system: yes

- name: Create NeoFS IR user
  ansible.builtin.user:
    name: '{{ neofs_ir__user }}'
    group: '{{ neofs_ir__group }}'
    password: '*'
    shell: '/usr/sbin/nologin'
    home: '{{ neofs_ir__data_dir }}'
    system: yes
    skeleton: no
